<?php

namespace App\Filament\Resources\Settings\Schemas;

use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\TimePicker;
use Filament\Forms\Components\Toggle;
use Filament\Schemas\Schema;

class SettingForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('app_name')
                    ->required()
                    ->default('Visa Office Chapai International'),
                TextInput::make('logo')
                    ->default(null),
                TextInput::make('favicon')
                    ->default(null),
                TextInput::make('office_phone')
                    ->tel()
                    ->default(null),
                TextInput::make('office_phone2')
                    ->tel()
                    ->default(null),
                Textarea::make('office_address')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('office_email')
                    ->email()
                    ->default(null),
                TextInput::make('whatsapp_number')
                    ->default(null),
                TextInput::make('facebook_url')
                    ->url()
                    ->default(null),
                TextInput::make('instagram_url')
                    ->url()
                    ->default(null),
                TextInput::make('primary_color')
                    ->required()
                    ->default('#3b82f6'),
                TextInput::make('secondary_color')
                    ->required()
                    ->default('#1e40af'),
                TextInput::make('tertiary_color')
                    ->required()
                    ->default('#10b981'),
                TextInput::make('currency')
                    ->required()
                    ->default('BDT'),
                TextInput::make('currency_symbol')
                    ->required()
                    ->default('৳'),
                TextInput::make('timezone')
                    ->required()
                    ->default('Asia/Dhaka'),
                TextInput::make('date_format')
                    ->required()
                    ->default('d/m/Y'),
                Toggle::make('maintenance_mode')
                    ->required(),
                Textarea::make('maintenance_message')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('smtp_host')
                    ->default(null),
                TextInput::make('smtp_port')
                    ->default(null),
                TextInput::make('smtp_username')
                    ->default(null),
                TextInput::make('smtp_password')
                    ->password()
                    ->default(null),
                TextInput::make('smtp_encryption')
                    ->default(null),
                TextInput::make('smtp_from_address')
                    ->default(null),
                TextInput::make('smtp_from_name')
                    ->default(null),
                Toggle::make('enable_email_marketing')
                    ->required(),
                Textarea::make('welcome_email_template')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('newsletter_template')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('promotional_template')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('reminder_template')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('email_marketing_schedule_days')
                    ->default(null)
                    ->columnSpanFull(),
                TimePicker::make('email_marketing_schedule_time'),
                TextInput::make('email_daily_limit')
                    ->numeric()
                    ->default(500),
                Toggle::make('email_tracking')
                    ->required(),
                Toggle::make('enable_sms_marketing')
                    ->required(),
                TextInput::make('sms_provider')
                    ->default(null),
                TextInput::make('sms_api_key')
                    ->default(null),
                TextInput::make('sms_api_secret')
                    ->default(null),
                TextInput::make('sms_sender_id')
                    ->default(null),
                TextInput::make('sms_api_url')
                    ->url()
                    ->default(null),
                Textarea::make('welcome_sms_template')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('promotional_sms_template')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('reminder_sms_template')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('sms_daily_limit')
                    ->required()
                    ->numeric()
                    ->default(100),
                TextInput::make('sms_unit_price')
                    ->required()
                    ->numeric()
                    ->default(0.5)
                    ->prefix('$'),
                Textarea::make('invoice_footer')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('terms_conditions')
                    ->default(null)
                    ->columnSpanFull(),
                Textarea::make('privacy_policy')
                    ->default(null)
                    ->columnSpanFull(),
                TextInput::make('invoice_prefix')
                    ->required()
                    ->default('INV-'),
                TextInput::make('google_analytics_id')
                    ->default(null),
            ]);
    }
}
